# Generated by Django 4.2.1 on 2023-11-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="number",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("aadhaar", models.BigIntegerField()),
            ],
        ),
    ]
