# Generated by Django 4.2.1 on 2023-11-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votingApp", "0002_number1_delete_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="number1",
            name="aadhaar",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
