# Generated by Django 4.2.1 on 2023-11-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votingApp", "0004_aadhaarnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="aadhaarnumber",
            name="otp",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
