# Generated by Django 4.2.1 on 2023-11-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "votingApp",
            "0008_rename_foundation_name_voteringlist_foundation_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="voteringlist",
            name="foundation_name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="voteringlist",
            name="leadername",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
