# Generated by Django 4.2.1 on 2023-11-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("votingApp", "0011_alter_votedata_leadername"),
    ]

    operations = [
        migrations.AddField(
            model_name="votedata",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="votingApp.aadhaarnumber",
            ),
        ),
    ]
