# Generated by Django 4.2.1 on 2023-11-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votingApp", "0014_alter_votedata_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="votedata", name="code", field=models.IntegerField(null=True),
        ),
    ]
